version: "3.8"
services:

    # PHP service
    app:
        build:
            context: ./docker/php8.1-fpm
            dockerfile: Dockerfile
        container_name: php-app
        working_dir: /var/www/
        volumes:
            - "${VOLUME_APP}:/var/www"
        networks:
            - app-network-auth
        extra_hosts:
            - "host.docker.internal:host-gateway"

    # Nginx service
    nginx:
        image: nginx:alpine
        container_name: php-nginx
        ports:
            - "${PORT_APP}:80"
        volumes:
            - "${VOLUME_APP}:/var/www"
            - "${VOLUME_NGINX_CONFIG}:/etc/nginx/conf.d/"
        networks:
            - app-network-auth

    # MySQL database service
    db:
        image: mysql:5.7
        container_name: mysql-db
        ports:
            - "${PORT_MYSQL}:${PORT_MYSQL}"
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        env_file:
            - ./.env
        restart: unless-stopped
        volumes:
            - "${VOLUME_MYSQL_DB}:/var/lib/mysql"
        networks:
            - app-network-auth

    # PHPMyAdmin database service
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5.0.1
        container_name: phpmyadmin
        restart: always
        environment:
            PMA_HOST: ${DB_HOST}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${PORT_PHPMYADMIN}:80"
        networks:
            - app-network-auth
            
networks:
    app-network-auth:
        driver: bridge